<script setup lang="ts">
import { computed, onMounted, ref, watch } from 'vue'; import { useRoute, useRouter } from 'vue-router'; import AppButton from '@/components/ui/AppButton.vue'; import { useChapterStore } from '@/stores/chapter'; import { workflowApi } from '@/api/workflow'; import type { DraftMode } from '@/types/chapter'
const route = useRoute(); const router = useRouter(); const projectId = String(route.params.projectId); const store = useChapterStore(); const selectedId = ref(String(route.params.chapterId || '')); const mode = ref<DraftMode>('generate'); const instruction = ref(''); const content = ref(''); const busy = ref(false); const message = ref('')
const selected = computed(() => store.chapters.find(chapter => chapter.id === selectedId.value)); const drafts = computed(() => store.drafts[selectedId.value] || [])
async function choose(id: string) { selectedId.value = id; await router.replace(`/projects/${projectId}/chapters/${id}`); try { const latest = await store.loadDrafts(id); content.value = latest[0]?.content || '' } catch { content.value = '' } }
async function generate() { if (!selectedId.value) return; busy.value = true; message.value = ''; try { const draft = await workflowApi.generateDraft(selectedId.value, mode.value, instruction.value); store.drafts[selectedId.value] = [draft, ...(store.drafts[selectedId.value] || [])]; content.value = draft.content; message.value = `已生成第 ${draft.version} 版草稿` } catch (e) { message.value = e instanceof Error ? e.message : '生成失败' } finally { busy.value = false } }
async function summary() { if (!selectedId.value) return; busy.value = true; try { await store.generateSummary(selectedId.value); message.value = '章节摘要已生成' } catch (e) { message.value = e instanceof Error ? e.message : '摘要生成失败' } finally { busy.value = false } }
onMounted(async () => { await store.loadChapters(projectId); if (selectedId.value && store.chapters.some(c => c.id === selectedId.value)) await choose(selectedId.value); else if (store.chapters[0]) await choose(store.chapters[0].id) })
watch(() => route.params.chapterId, id => { if (id && String(id) !== selectedId.value) choose(String(id)) })
</script>
<template><section><div class="mb-6 flex flex-wrap items-end justify-between gap-4"><div><p class="page-kicker">04 / WRITING</p><h2 class="page-heading">章节写作</h2><p class="page-copy mt-2">基于大纲与章节关系生成草稿，并保留版本记录。</p></div><AppButton variant="secondary" :loading="busy" @click="summary">生成章节摘要</AppButton></div><p v-if="message" class="mb-4 text-sm" :class="message.includes('失败') ? 'text-red-700' : 'text-teal-800'">{{ message }}</p><div class="grid gap-4 xl:grid-cols-[200px_minmax(0,1fr)_220px]"><aside class="panel"><p class="panel-heading">大纲</p><button v-for="chapter in store.chapters" :key="chapter.id" class="block w-full border-b border-stone-100 px-4 py-3 text-left text-sm hover:bg-stone-50" :class="selectedId === chapter.id ? 'bg-teal-50 text-teal-900' : 'text-stone-700'" :style="{ paddingLeft: `${16 + (chapter.level - 1) * 12}px` }" @click="choose(chapter.id)">{{ chapter.title }}</button></aside><div class="min-w-0"><div class="panel"><div class="flex items-center justify-between border-b border-stone-200 px-5 py-4"><div><h3 class="text-sm font-semibold">{{ selected?.title || '选择章节' }}</h3><p class="mt-1 text-xs text-stone-500">{{ selected?.purpose || '暂无章节目的' }}</p></div><span class="text-xs text-stone-500">{{ content.length }} 字符</span></div><textarea v-model="content" class="block min-h-[580px] w-full border-0 bg-white p-5 font-mono text-sm leading-7 outline-none focus:ring-1 focus:ring-inset focus:ring-teal-700" placeholder="生成草稿后，可在这里继续编辑。" /></div></div><aside class="grid content-start gap-4"><div class="panel"><div class="panel-heading">生成控制</div><div class="panel-body grid gap-3"><label><span class="field-label">模式</span><select v-model="mode" class="field-control h-9"><option value="generate">生成</option><option value="rewrite">改写</option><option value="continue">续写</option><option value="expand">扩写</option><option value="compress">压缩</option><option value="polish">润色</option></select></label><label><span class="field-label">补充指令</span><textarea v-model="instruction" class="field-control" rows="4" placeholder="例如：更强调方法比较。" /></label><AppButton :loading="busy" @click="generate">生成草稿</AppButton></div></div><div class="panel"><div class="panel-heading">最新草稿</div><button v-for="draft in drafts" :key="draft.id" class="block w-full border-b border-stone-100 px-4 py-3 text-left text-sm hover:bg-stone-50" @click="content = draft.content"><span class="font-medium">版本 {{ draft.version }}</span><span class="ml-2 text-xs text-stone-500">{{ draft.generation_mode }}</span></button><p v-if="!drafts.length" class="p-4 text-xs text-stone-500">尚无草稿版本。</p></div></aside></div></section></template>
