<script setup lang="ts">
import { onMounted, ref } from 'vue'; import { useRoute } from 'vue-router'; import AppButton from '@/components/ui/AppButton.vue'; import { useChapterStore } from '@/stores/chapter'; import { workflowApi } from '@/api/workflow'; import type { IssueSeverity } from '@/types/chapter'
const projectId = String(useRoute().params.projectId); const store = useChapterStore(); const busy = ref(false); const message = ref(''); const colors: Record<IssueSeverity, string> = { high: 'border-red-200 bg-red-50 text-red-700', medium: 'border-amber-200 bg-amber-50 text-amber-800', low: 'border-stone-200 bg-stone-50 text-stone-600' }
async function load() { try { await store.loadReviewIssues(projectId) } catch { /* no issues yet */ } }
async function run() { busy.value = true; try { store.reviewIssues = await workflowApi.generateReview(projectId); message.value = '一致性检查已完成' } catch (e) { message.value = e instanceof Error ? e.message : '检查失败' } finally { busy.value = false } }
async function update(id: string, status: 'fixed' | 'ignored') { const issue = await workflowApi.updateIssue(projectId, id, { status }); const index = store.reviewIssues.findIndex(item => item.id === id); if (index >= 0) store.reviewIssues[index] = issue }
onMounted(load)
</script>
<template><section><div class="mb-6 flex flex-wrap items-end justify-between gap-4"><div><p class="page-kicker">05 / REVIEW</p><h2 class="page-heading">一致性校验</h2><p class="page-copy mt-2">检查 Brief、章节结构和草稿之间的矛盾与缺口。</p></div><AppButton :loading="busy" @click="run">运行一致性检查</AppButton></div><p v-if="message" class="mb-4 text-sm text-teal-800">{{ message }}</p><div v-if="!store.reviewIssues.length" class="border-y border-stone-200 py-14 text-center text-sm text-stone-500">运行检查后，问题会按严重程度列在这里。</div><div v-else class="grid gap-3"><article v-for="issue in store.reviewIssues" :key="issue.id" class="panel border-l-4 p-5" :class="colors[issue.severity]"><div class="flex flex-wrap items-start justify-between gap-4"><div><div class="mb-2 flex gap-2 text-xs"><span class="border border-current px-2 py-0.5">{{ issue.severity }}</span><span>{{ issue.type }}</span></div><h3 class="font-semibold text-stone-900">{{ issue.description }}</h3><p v-if="issue.suggestion" class="mt-2 text-sm leading-6 text-stone-600">建议：{{ issue.suggestion }}</p></div><div v-if="issue.status === 'open'" class="flex gap-2"><AppButton variant="secondary" @click="update(issue.id, 'ignored')">忽略</AppButton><AppButton @click="update(issue.id, 'fixed')">标记已修复</AppButton></div><span v-else class="text-sm text-stone-500">{{ issue.status === 'fixed' ? '已修复' : '已忽略' }}</span></div></article></div></section></template>
