<script setup lang="ts">
import { computed, onMounted, ref } from 'vue'; import { useRoute } from 'vue-router'; import AppButton from '@/components/ui/AppButton.vue'; import { useChapterStore } from '@/stores/chapter'; import { workflowApi } from '@/api/workflow'
const projectId = String(useRoute().params.projectId); const store = useChapterStore(); const busy = ref(false); const message = ref(''); const preview = ref('')
const ordered = computed(() => [...store.chapters].sort((a, b) => a.order - b.order))
async function load() { await store.loadChapters(projectId); await Promise.all(ordered.value.map(async chapter => { try { await store.loadDrafts(chapter.id) } catch { /* chapter has no draft */ } })); preview.value = ordered.value.map(chapter => { const content = store.drafts[chapter.id]?.[0]?.content || ''; return content ? `# ${chapter.title}\n\n${content}` : '' }).filter(Boolean).join('\n\n---\n\n') }
async function exportFile(format: 'markdown' | 'docx') { busy.value = true; try { const result = format === 'markdown' ? await workflowApi.exportMarkdown(projectId) : await workflowApi.exportDocx(projectId); window.open(workflowApi.downloadUrl(result.id), '_blank'); message.value = `${format === 'markdown' ? 'Markdown' : 'Word'} 文件已生成` } catch (e) { message.value = e instanceof Error ? e.message : '导出失败' } finally { busy.value = false } }
onMounted(() => { load().catch(e => { message.value = e instanceof Error ? e.message : '加载预览失败' }) })
</script>
<template><section><div class="mb-6 flex flex-wrap items-end justify-between gap-4"><div><p class="page-kicker">06 / EXPORT</p><h2 class="page-heading">导出文稿</h2><p class="page-copy mt-2">预览最新章节版本，再导出为可交付文件。</p></div><div class="flex gap-2"><AppButton variant="secondary" :loading="busy" @click="exportFile('markdown')">导出 Markdown</AppButton><AppButton :loading="busy" @click="exportFile('docx')">导出 Word</AppButton></div></div><p v-if="message" class="mb-4 text-sm" :class="message.includes('失败') ? 'text-red-700' : 'text-teal-800'">{{ message }}</p><div class="panel"><div class="flex items-center justify-between border-b border-stone-200 px-5 py-4"><h3 class="text-sm font-semibold">合并预览</h3><span class="text-xs text-stone-500">{{ ordered.length }} 个章节</span></div><pre class="min-h-[540px] whitespace-pre-wrap p-5 font-mono text-sm leading-7 text-stone-700">{{ preview || '暂无草稿内容。完成章节写作后，最新版本会出现在这里。' }}</pre></div></section></template>
