<script setup lang="ts">
import { reactive, ref } from 'vue'; import { useRoute } from 'vue-router'; import AppButton from '@/components/ui/AppButton.vue'; import AppField from '@/components/ui/AppField.vue'; import { projectsApi } from '@/api/projects'; import type { ProjectBrief, ProjectContextPayload } from '@/types/project'
const projectId = String(useRoute().params.projectId); const busy = ref(false); const message = ref(''); const brief = ref<ProjectBrief | null>(null)
const form = reactive<Record<string, string>>({ background: '', problem: '', goal: '', scenario: '', target_users: '', technologies: '', modules: '', architecture: '', environment: '', experiments: '', writing_preferences: '' })
const label: Record<string, string> = { background: '研究背景', problem: '核心问题', goal: '研究目标', scenario: '应用场景', target_users: '目标用户', technologies: '技术与方法', modules: '系统模块', architecture: '整体架构', environment: '实验环境', experiments: '实验设计', writing_preferences: '写作偏好' }
function payload(): ProjectContextPayload { return { background: form.background, problem: form.problem, goal: form.goal, scenario: form.scenario, target_users: form.target_users, technologies: form.technologies.split(/[，,\n]/).filter(Boolean), modules: form.modules.split(/[，,\n]/).filter(Boolean), architecture: form.architecture, environment: form.environment, experiments: form.experiments, writing_prefs: form.writing_preferences ? { notes: form.writing_preferences } : null } }
async function save() { busy.value = true; message.value = ''; try { await projectsApi.saveContext(projectId, payload()); message.value = '上下文已保存' } catch (e) { message.value = e instanceof Error ? e.message : '保存失败' } finally { busy.value = false } }
async function generate() { await save(); if (message.value !== '上下文已保存') return; busy.value = true; try { brief.value = await projectsApi.generateBrief(projectId); message.value = 'Brief 已生成' } catch (e) { message.value = e instanceof Error ? e.message : '生成失败' } finally { busy.value = false } }
</script>
<template><section><div class="mb-6 flex flex-wrap items-end justify-between gap-4"><div><p class="page-kicker">01 / BRIEF</p><h2 class="page-heading">研究上下文</h2><p class="page-copy mt-2">把已知条件写清楚，生成结果会更稳定。</p></div><div class="flex gap-2"><AppButton variant="secondary" :loading="busy" @click="save">保存上下文</AppButton><AppButton :loading="busy" @click="generate">生成 Brief</AppButton></div></div><p v-if="message" class="mb-4 text-sm" :class="message.includes('失败') ? 'text-red-700' : 'text-teal-800'">{{ message }}</p><div class="grid gap-4 xl:grid-cols-2"><div class="panel"><div class="panel-heading">研究设定</div><div class="panel-body grid gap-4"><AppField v-for="key in ['background','problem','goal','scenario','target_users']" :key="key" v-model="form[key]" :label="label[key]" textarea :rows="3" /></div></div><div class="panel"><div class="panel-heading">方案与写作约束</div><div class="panel-body grid gap-4"><AppField v-for="key in ['technologies','modules','architecture','environment','experiments','writing_preferences']" :key="key" v-model="form[key]" :label="label[key]" textarea :rows="3" /></div></div></div><div v-if="brief" class="panel mt-4"><div class="panel-heading">生成的 Project Brief</div><div class="panel-body grid gap-5 md:grid-cols-2"><div v-for="item in [{label:'题目说明',value:brief.title_explanation},{label:'研究意义',value:brief.significance},{label:'技术路线',value:brief.technical_route},{label:'预期成果',value:brief.expected_result},{label:'写作边界',value:brief.writing_boundary}]" :key="item.label"><p class="field-label">{{ item.label }}</p><p class="whitespace-pre-wrap text-sm leading-6 text-stone-700">{{ item.value || '—' }}</p></div></div></div></section></template>
