<script setup lang="ts">
import { ref } from 'vue'
import { useRouter } from 'vue-router'
import AppButton from '@/components/ui/AppButton.vue'; import AppField from '@/components/ui/AppField.vue'; import { useProjectStore } from '@/stores/project'; import type { ProjectCreate } from '@/types/project'
const router = useRouter(); const store = useProjectStore(); const saving = ref(false); const error = ref('')
const form = ref<ProjectCreate>({ type: 'thesis', title: '', major: '', school: '', target_word_count: 8000, language: 'zh-CN', requirements: '' })
async function submit() { if (!form.value.title.trim()) { error.value = '请填写项目标题'; return }; saving.value = true; error.value = ''; try { const project = await store.createProject(form.value); await router.push(`/projects/${project.id}/brief`) } catch (e) { error.value = e instanceof Error ? e.message : '创建失败' } finally { saving.value = false } }
</script>
<template><section class="mx-auto max-w-3xl"><div class="mb-7"><p class="page-kicker">NEW PROJECT</p><h1 class="page-heading">新建写作项目</h1><p class="page-copy mt-2">先填写标题和类型，创建后可直接用模型生成 Project Brief。</p></div><form class="panel" @submit.prevent="submit"><div class="panel-body grid gap-5 sm:grid-cols-2"><label><span class="field-label">项目类型</span><select v-model="form.type" class="field-control h-9"><option value="thesis">毕业论文</option><option value="course_report">课程报告</option><option value="proposal">开题报告</option></select></label><AppField v-model="form.title" label="项目标题" /><AppField v-model="form.major" label="专业" /><AppField v-model="form.school" label="学校 / 院系" /><label><span class="field-label">目标字数</span><input v-model.number="form.target_word_count" class="field-control h-9" type="number" min="1" /></label><label><span class="field-label">写作语言</span><select v-model="form.language" class="field-control h-9"><option value="zh-CN">中文</option><option value="en-US">English</option></select></label><div class="sm:col-span-2"><AppField v-model="form.requirements" label="任务要求" textarea :rows="5" hint="可填写格式、重点章节、提交要求或参考资料范围。" /></div></div><div class="flex items-center justify-between border-t border-stone-200 px-5 py-4"><p v-if="error" class="text-sm text-red-700">{{ error }}</p><span v-else class="status-note">创建后将进入 Brief 页，可一键根据标题生成。</span><AppButton type="submit" :loading="saving">创建并生成 Brief</AppButton></div></form></section></template>
